# Generated by Django 6.1.1 on 2026-09-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Patient', 'Patient'), ('Dentist', 'Dentist'), ('Doctor', 'Doctor'), ('Receptionist', 'Receptionist'), ('Admin', 'Admin')], default='Patient', max_length=20),
        ),
    ]
