# Generated by Django 6.1.1 on 2026-09-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_appointment_patient_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='receptionist_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Needs_Reschedule', 'Needs Reschedule'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
